In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, confusion_matrix

# Load the data from CSV file
df = pd.read_csv('phishing.csv')

# Split data into input (X) and output (Y) variables
X = df.iloc[:, 1:31].values
Y = df.iloc[:, 31].values

# Scale the input data
sc = MinMaxScaler(feature_range = (0, 1))
X = sc.fit_transform(X)

# Reshape input data to be 3D array for LSTM
X = np.reshape(X, (X.shape[0], X.shape[1], 1))

# Split the data into training and testing sets
split = int(0.7 * len(df))
X_train, Y_train = X[:split], Y[:split]
X_test, Y_test = X[split:], Y[split:]

# Build the LSTM model
model = Sequential()
model.add(LSTM(units=64, return_sequences=True, input_shape=(X.shape[1], 1)))
model.add(Dropout(0.2))
model.add(LSTM(units=64, return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(units=64))
model.add(Dropout(0.2))
model.add(Dense(units=1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, Y_train, epochs=1, batch_size=32)

# Make predictions on test set
Y_pred = model.predict(X_test)
Y_pred = (Y_pred > 0.5)

# Evaluate the model
accuracy = accuracy_score(Y_test, Y_pred)
conf_matrix = confusion_matrix(Y_test, Y_pred)
print("Accuracy: ", accuracy)
print("Confusion Matrix: ")
print(conf_matrix)

104/104 [==============================] - 5s 24ms/step
Accuracy:  0.0
Confusion Matrix: 
[[   0 1464    0]
 [   0    0    0]
 [   0 1853    0]]
